### PR TITLE
Fixing-run-op

### PR DESCRIPTION
**Pull request by matsonj**

### CODE REVIEW

**Comment by matsonj** [comment]
@mermelstein so the db creds are failing to authenticate, even after the github actions hiccup. It looks like an issue related to auth? `fatal: password authentication failed for user ‘***’`

**Comment by mermelstein** [comment]
@matsonj weird, I just connected fine via DBeaver. Also looks like max concurrent connections is 81 and we have not hit that

**Comment by mermelstein** [comment]
very odd, ran this repo locally totally fine. Possibly GH Actions still having issues?

Screenshot 2023-09-26 at 10 07 53 PM

**Comment by matsonj** [comment]
Merging anyway, lets see if the schedule jobs sort this out.

**Pull request merged**
